# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [ ]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [3]:
iris = datasets.load_iris()

In [4]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data,
                                                                                     iris.target, 
                                                                                     test_size = 0.3)

In [5]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [6]:
print ('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [7]:
print ('Обучающая выборка:\n', train_data[:5])
print ('\n')
print ('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[7.7 3.  6.1 2.3]
 [5.6 2.9 3.6 1.3]
 [6.4 3.2 4.5 1.5]
 [5.8 4.  1.2 0.2]
 [5.5 2.6 4.4 1.2]]


Тестовая выборка:
 [[5.5 2.3 4.  1.3]
 [5.7 2.5 5.  2. ]
 [6.8 2.8 4.8 1.4]
 [6.2 2.2 4.5 1.5]
 [5.1 3.5 1.4 0.2]]


In [8]:
print ('Метки классов на обучающей выборке:\n', train_labels)
print ('\n')
print ('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [2 1 1 0 1 1 1 1 1 0 2 0 0 2 0 1 2 0 1 2 1 2 1 0 0 1 0 1 2 2 2 0 1 2 0 0 1
 0 1 2 0 1 2 2 2 0 2 2 1 0 0 2 0 0 0 1 1 2 0 1 2 0 0 0 2 0 0 1 1 1 0 0 1 0
 0 2 0 1 0 2 1 0 1 2 1 0 2 1 1 0 0 2 1 2 0 0 1 0 0 1 2 2 1 2 1]


Метки классов на тестовой выборке:
 [1 2 1 1 0 1 0 2 1 2 2 1 0 2 0 2 0 2 2 2 1 2 2 1 1 2 2 1 1 0 2 2 2 0 2 1 2
 2 0 0 2 1 2 0 1]


### Стратегии проведения кросс-валидации

#### KFold

Генерирует список индексов разбиения на выборки для обучения и теста

In [9]:
for train_indices, test_indices in cross_validation.KFold(10, #размер данных
                                                          n_folds = 5): #количество разбиений
    print (train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


Заметим, что список в исходном порядке - для отсортировки:

In [10]:
for train_indices, test_indices in cross_validation.KFold(10,
                                                          n_folds = 2,
                                                          shuffle = True):
    print (train_indices, test_indices)

[0 1 2 3 5] [4 6 7 8 9]
[4 6 7 8 9] [0 1 2 3 5]


Для фиксации разбиения:

In [11]:
for train_indices, test_indices in cross_validation.KFold(10,
                                                          n_folds = 2,
                                                          shuffle = True,
                                                          random_state = 1):
    print train_indices, test_indices

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(train_indices, test_indices)? (<ipython-input-11-97d4948017be>, line 5)

#### StratifiedKFold

Для сохранения баланса класса по меткам

In [12]:
target = np.array([0] * 5 + [1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target,
                                                                    n_folds = 2,
                                                                    shuffle = True,
                                                                    random_state = 0):
    print (train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [13]:
target = np.array([0, 1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target,
                                                                    n_folds = 2,
                                                                    shuffle = True):
    print (train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[4 5 6 7] [0 1 2 3 8 9]
[0 1 2 3 8 9] [4 5 6 7]


#### ShuffleSplit

Случайное разбиение

In [19]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10,
                                                                 n_iter = 10,
                                                                 test_size = 0.2):
    print (train_indices, test_indices)

[7 9 3 2 6 1 0 4] [5 8]
[8 3 7 5 1 6 0 2] [9 4]
[4 3 0 1 2 9 5 6] [8 7]
[0 6 4 1 7 5 3 2] [8 9]
[8 7 1 5 3 9 4 6] [0 2]
[9 3 6 1 5 0 2 8] [4 7]
[9 0 8 7 6 4 5 1] [3 2]
[1 7 8 2 9 3 5 6] [4 0]
[5 6 4 7 1 0 3 8] [9 2]
[7 0 9 3 6 8 2 4] [5 1]


#### StratifiedShuffleSplit

Случайное разбиение с исходным соотношением классов

In [17]:
target = np.array([0] * 5 + [1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target,
                                                                           n_iter = 4,
                                                                           test_size = 0.2):
    print (train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[4 6 1 9 8 5 2 0] [3 7]
[9 3 7 2 5 8 0 4] [6 1]
[8 4 6 9 0 2 7 1] [5 3]
[6 2 8 4 0 9 7 3] [5 1]


#### Leave-One-Out

Разбиение с одним объектом в тесте

In [18]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print (train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators